#matrix:
#  include:
os: osx
language: objective-c
osx_image: xcode10.1
before_script:
- pip install six
- brew update
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller
- brew install ios-deploy
- git clone https://github.com/flutter/flutter.git -b alpha --depth 1
script:
- ./flutter/bin/flutter packages get
- ./flutter/bin/flutter analyze
- (cd example && ./flutter/bin/flutter packages get)
- (cd example && ./flutter/bin/flutter analyze)
- (cd example && ./flutter/bin/flutter test)

cache:
  directories:
    - $HOME/.pub-cache
